### ISSUE TITLE
First pass

### ISSUE THREAD

**Issue by syoes03** [NicmeisteR/Halo-dBot#1]
The join link is broken or not valid
"Add to Discord" button seems unresponsive
The "see features" text color is hard to see since the button is white and the text is a light gray. 
I would prefer to have the Discord server & Patreon widgets on the home screen.

What do you think about removing the see features button and moving the features closer like  y-100px ? including the main title and subtext

**Comment by NicmeisteR** [comment]
Fixes applied:

- [✔] Generated and added new Discord join link.
- [✔] Add to Discord button fixed.
- [✔] "See Features" button color corrected.
- [✔]  Added Patron widget and added more focus on the join button.
- [✔]  Adjusted spacing of home page and changed "See Features" to "View Commands"
- [❌]  Discord Server Widget

Inspecting ways to add the discord widget without cluttering the design.
Also inspecting ways to improve overall layout of home page.
